apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cnapp-keyvault-secrets
  namespace: ${NAMESPACE}
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${KEYVAULT_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEYVAULT_NAME}"
    tenantId: "${ARM_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: ${BACKEND_SECRET_NAME}
          objectType: secret
          objectAlias: backend-secret
        - |
          objectName: ${FRONTEND_SECRET_NAME}
          objectType: secret
          objectAlias: frontend-secret
